import Image from 'next/image';

const iconMap = new Map();
iconMap.set("404", (props) => <Image src="/icons/404.png" alt="404" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("annona", (props) => <Image src="/icons/annona.png" alt="annona" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("apple", (props) => <Image src="/icons/apple.png" alt="apple" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("apricot", (props) => <Image src="/icons/apricot.png" alt="apricot" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("avocado", (props) => <Image src="/icons/avocado.png" alt="avocado" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("banana", (props) => <Image src="/icons/banana.png" alt="banana" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("blackberry", (props) => <Image src="/icons/blackberry.png" alt="blackberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("blueberry", (props) => <Image src="/icons/blueberry.png" alt="blueberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("cantaloupe", (props) => <Image src="/icons/cantaloupe.png" alt="cantaloupe" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("ceylon gooseberry", (props) => <Image src="/icons/ceylon gooseberry.png" alt="ceylon gooseberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("cherry", (props) => <Image src="/icons/cherry.png" alt="cherry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("cranberry", (props) => <Image src="/icons/cranberry.png" alt="cranberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("dragonfruit", (props) => <Image src="/icons/dragonfruit.png" alt="dragonfruit" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("durian", (props) => <Image src="/icons/durian.png" alt="durian" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("feijoa", (props) => <Image src="/icons/feijoa.png" alt="feijoa" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("fig", (props) => <Image src="/icons/fig.png" alt="fig" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("gooseberry", (props) => <Image src="/icons/gooseberry.png" alt="gooseberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("grape", (props) => <Image src="/icons/grape.png" alt="grape" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("grapefruit", (props) => <Image src="/icons/grapefruit.png" alt="grapefruit" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("greenapple", (props) => <Image src="/icons/greenapple.png" alt="greenapple" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("guava", (props) => <Image src="/icons/guava.png" alt="guava" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("hazelnut", (props) => <Image src="/icons/hazelnut.png" alt="hazelnut" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("horned melon", (props) => <Image src="/icons/horned melon.png" alt="horned melon" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("jackfruit", (props) => <Image src="/icons/jackfruit.png" alt="jackfruit" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("japanese persimmon", (props) => <Image src="/icons/japanese persimmon.png" alt="japanese persimmon" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("kiwi", (props) => <Image src="/icons/kiwi.png" alt="kiwi" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("kiwifruit", (props) => <Image src="/icons/kiwifruit.png" alt="kiwifruit" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("lemon", (props) => <Image src="/icons/lemon.png" alt="lemon" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("lime", (props) => <Image src="/icons/lime.png" alt="lime" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("lingonberry", (props) => <Image src="/icons/lingonberry.png" alt="lingonberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("longan", (props) => <Image src="/icons/longan.png" alt="longan" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("lychee", (props) => <Image src="/icons/lychee.png" alt="lychee" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("mango", (props) => <Image src="/icons/mango.png" alt="mango" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("mangosteen", (props) => <Image src="/icons/mangosteen.png" alt="mangosteen" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("melon", (props) => <Image src="/icons/melon.png" alt="melon" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("morus", (props) => <Image src="/icons/morus.png" alt="morus" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("orange", (props) => <Image src="/icons/orange.png" alt="orange" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("papaya", (props) => <Image src="/icons/papaya.png" alt="papaya" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("passionfruit", (props) => <Image src="/icons/passionfruit.png" alt="passionfruit" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("peach", (props) => <Image src="/icons/peach.png" alt="peach" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pear", (props) => <Image src="/icons/pear.png" alt="pear" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("persimmon", (props) => <Image src="/icons/persimmon.png" alt="persimmon" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pineapple", (props) => <Image src="/icons/pineapple.png" alt="pineapple" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pitahaya", (props) => <Image src="/icons/pitahaya.png" alt="pitahaya" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("plum", (props) => <Image src="/icons/plum.png" alt="plum" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pomegranate", (props) => <Image src="/icons/pomegranate.png" alt="pomegranate" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pomelo", (props) => <Image src="/icons/pomelo.png" alt="pomelo" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("pumpkin", (props) => <Image src="/icons/pumpkin.png" alt="pumpkin" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("raspberry", (props) => <Image src="/icons/raspberry.png" alt="raspberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("sapodilla", (props) => <Image src="/icons/sapodilla.png" alt="sapodilla" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("strawberry", (props) => <Image src="/icons/strawberry.png" alt="strawberry" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("tangerine", (props) => <Image src="/icons/tangerine.png" alt="tangerine" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("tomato", (props) => <Image src="/icons/tomato.png" alt="tomato" width={props.width || 30} height={props.height || 30} {...props} />); 
iconMap.set("watermelon", (props) => <Image src="/icons/watermelon.png" alt="watermelon" width={props.width || 30} height={props.height || 30} {...props} />); 


export default iconMap;
